import type { DB, Product } from "./types";

const base = {
  active: true,
  images: [] as string[],
  createdAt: "2026-10-01T00:00:00.000Z",
};

const products: Product[] = [
  {
    ...base,
    id: "p1",
    slug: "oud-noir",
    name: "Oud Noir",
    tagline: "Smoked oud, saffron and midnight leather.",
    description:
      "Our signature. Aged Cambodian oud wrapped in saffron threads and Taif rose, settling into a warm trail of amber and soft leather. Bold at first spray, intimate by evening.",
    category: "Oud",
    gender: "Unisex",
    price: 4999,
    offerPrice: 3999,
    sizeMl: 100,
    stock: 24,
    bestSeller: true,
    notes: { top: ["Saffron", "Pink pepper"], heart: ["Cambodian oud", "Taif rose"], base: ["Amber", "Leather", "Patchouli"] },
    features: ["Extrait de parfum, 25% concentration", "Lasts 12+ hours on skin", "Aged 90 days before bottling", "Hand-finished zamac cap"],
    color: "#4a2516",
    bottle: "facet",
    longevity: 5,
    sillage: 5,
  },
  {
    ...base,
    id: "p2",
    slug: "rose-absolue",
    name: "Rose Absolue",
    tagline: "A thousand petals at dawn.",
    description:
      "Bulgarian rose absolute and lychee glisten over a heart of peony, resting on white musk and cashmere wood. Romantic, luminous, unmistakably modern.",
    category: "Floral",
    gender: "Women",
    price: 3499,
    offerPrice: null,
    sizeMl: 50,
    stock: 40,
    bestSeller: true,
    notes: { top: ["Lychee", "Bergamot"], heart: ["Bulgarian rose", "Peony"], base: ["White musk", "Cashmere wood"] },
    features: ["Eau de parfum, 20% concentration", "Lasts 8 to 10 hours", "Vegan and cruelty free", "Refillable glass bottle"],
    color: "#c9737f",
    bottle: "round",
    longevity: 4,
    sillage: 3,
  },
  {
    ...base,
    id: "p3",
    slug: "ambre-soleil",
    name: "Ambre Soleil",
    tagline: "Golden resin warmed by the sun.",
    description:
      "Labdanum and benzoin melt into vanilla bourbon and tonka, lifted by a twist of blood orange. A glowing amber that feels like late afternoon light on skin.",
    category: "Amber",
    gender: "Unisex",
    price: 3999,
    offerPrice: 3199,
    sizeMl: 100,
    stock: 15,
    bestSeller: false,
    notes: { top: ["Blood orange", "Cardamom"], heart: ["Labdanum", "Benzoin"], base: ["Bourbon vanilla", "Tonka bean"] },
    features: ["Eau de parfum, 22% concentration", "Lasts 10+ hours", "Perfect for evenings and winter", "Magnetic gold cap"],
    color: "#c97a22",
    bottle: "classic",
    longevity: 4,
    sillage: 4,
  },
  {
    ...base,
    id: "p4",
    slug: "bois-sacre",
    name: "Bois Sacré",
    tagline: "Sandalwood temples and cedar smoke.",
    description:
      "Mysore sandalwood and Atlas cedar meet a ribbon of frankincense and vetiver. Dry, meditative and quietly powerful, made for those who prefer to be remembered than noticed.",
    category: "Woody",
    gender: "Men",
    price: 4299,
    offerPrice: null,
    sizeMl: 100,
    stock: 8,
    bestSeller: true,
    notes: { top: ["Elemi", "Black pepper"], heart: ["Frankincense", "Atlas cedar"], base: ["Mysore sandalwood", "Vetiver"] },
    features: ["Extrait de parfum, 24% concentration", "Lasts 12+ hours", "Sustainably sourced sandalwood", "Signed batch number"],
    color: "#6b4a2b",
    bottle: "tall",
    longevity: 5,
    sillage: 4,
  },
  {
    ...base,
    id: "p5",
    slug: "aqua-lumiere",
    name: "Aqua Lumière",
    tagline: "Sea salt, citrus and open skies.",
    description:
      "Calabrian bergamot and sea salt splash over sage and ambergris. A clean, energising fragrance for hot days and long journeys.",
    category: "Fresh",
    gender: "Men",
    price: 2999,
    offerPrice: 2499,
    sizeMl: 100,
    stock: 30,
    bestSeller: false,
    notes: { top: ["Bergamot", "Sea salt"], heart: ["Sage", "Marine accord"], base: ["Ambergris", "Driftwood"] },
    features: ["Eau de parfum, 18% concentration", "Lasts 6 to 8 hours", "Ideal for summer and office wear", "Travel-friendly bottle"],
    color: "#4f97ad",
    bottle: "classic",
    longevity: 3,
    sillage: 3,
  },
  {
    ...base,
    id: "p6",
    slug: "musc-blanc",
    name: "Musc Blanc",
    tagline: "Clean skin, soft linen, quiet comfort.",
    description:
      "A cloud of white musk and iris over pear and cotton flower. Soft, close to skin and endlessly wearable, like your favourite sweater in scent form.",
    category: "Floral",
    gender: "Women",
    price: 2799,
    offerPrice: null,
    sizeMl: 50,
    stock: 0,
    bestSeller: false,
    notes: { top: ["Pear", "Aldehydes"], heart: ["Iris", "Cotton flower"], base: ["White musk", "Ambrette"] },
    features: ["Eau de parfum, 18% concentration", "Lasts 6 to 8 hours", "Skin-safe, alcohol-light formula", "Everyday signature scent"],
    color: "#d9cbb5",
    bottle: "round",
    longevity: 3,
    sillage: 2,
  },
  {
    ...base,
    id: "p7",
    slug: "velvet-saffron",
    name: "Velvet Saffron",
    tagline: "Spiced oud on crimson velvet.",
    description:
      "Kashmiri saffron and raspberry over a rich heart of oud and rose, finished with a resinous base of myrrh and vanilla. Opulent and unforgettable.",
    category: "Oud",
    gender: "Unisex",
    price: 5499,
    offerPrice: 4699,
    sizeMl: 100,
    stock: 5,
    bestSeller: true,
    notes: { top: ["Kashmiri saffron", "Raspberry"], heart: ["Oud", "Damask rose"], base: ["Myrrh", "Vanilla", "Musk"] },
    features: ["Extrait de parfum, 28% concentration", "Lasts 14+ hours", "Limited small-batch release", "Velvet-lined gift box"],
    color: "#8f2430",
    bottle: "tall",
    longevity: 5,
    sillage: 5,
  },
  {
    ...base,
    id: "p8",
    slug: "neroli-riviera",
    name: "Neroli Riviera",
    tagline: "Orange blossom on a Mediterranean terrace.",
    description:
      "Tunisian neroli and petitgrain sparkle over orange blossom and jasmine, drying down to a soft vetiver and musk. Effortless sunshine in a bottle.",
    category: "Fresh",
    gender: "Unisex",
    price: 3299,
    offerPrice: null,
    sizeMl: 75,
    stock: 22,
    bestSeller: false,
    notes: { top: ["Neroli", "Petitgrain"], heart: ["Orange blossom", "Jasmine"], base: ["Vetiver", "Musk"] },
    features: ["Eau de parfum, 20% concentration", "Lasts 7 to 9 hours", "Bright daytime fragrance", "Recyclable packaging"],
    color: "#dba640",
    bottle: "facet",
    longevity: 3,
    sillage: 3,
  },
];

export const seed: DB = {
  products,
  testimonials: [
    { id: "t1", name: "Ayesha R.", location: "Kochi", rating: 5, product: "Oud Noir", quote: "I get stopped every single time I wear Oud Noir. It lasts from morning prayers until I sleep. Nothing else in my collection comes close." },
    { id: "t2", name: "Rahul M.", location: "Bengaluru", rating: 5, product: "Bois Sacré", quote: "Feels like a niche fragrance at a fraction of the price. The sandalwood is creamy and real, not that synthetic sharpness." },
    { id: "t3", name: "Fatima K.", location: "Dubai", rating: 5, product: "Velvet Saffron", quote: "The packaging alone felt like a gift. The saffron opening is gorgeous and the dry down is pure velvet." },
    { id: "t4", name: "Neha S.", location: "Mumbai", rating: 4, product: "Rose Absolue", quote: "A rose that doesn't smell old fashioned. Fresh, juicy and so elegant. Ordering on WhatsApp was quick and easy." },
    { id: "t5", name: "Arjun P.", location: "Kozhikode", rating: 5, product: "Aqua Lumière", quote: "My daily office scent now. Clean, fresh and people keep asking what I'm wearing. Delivery was in two days." },
    { id: "t6", name: "Sara A.", location: "Doha", rating: 5, product: "Ambre Soleil", quote: "Warm, cosy and incredibly long lasting. I sprayed it on a scarf and it still smelled amazing a week later." },
  ],
  settings: {
    whatsapp: "919562195579",
    currencySymbol: "₹",
    currencyCode: "INR",
    email: "hello@maisonelan.com",
    phone: "+91 98765 43210",
    address: "MG Road, Kochi, Kerala, India",
    instagram: "https://instagram.com/",
    announcement: "Festive offer: up to 20% off selected fragrances. Free delivery across India.",
  },
};
